argv
DarkHunteR73/MaxiOracleTask pull request #31
Opened 2022-10-11 17:58 UTC by DarkHunteR73

2022-10-12 07:50 UTC, olgapshen requested changes
Молодец. Доделай или отпишись почему считаешь что некоторые вещи нужно оставить как есть, и пойдём дальше. Нужно распарсить значения с командной строки, и я жду скриптов автоматизации для локальной сборки и запуска докера )

2022-10-12 07:50 UTC, olgapshen commented on dal.cpp
>  }
Нет новой строки:

[ throw std::invalid_argument("Invalid argument](https://github.com/olgapshen/Sysbase#%D1%81%D1%82%D0%B8%D0%BB%D1%8C-%D0%BA%D0%BE%D0%B4%D0%B0)

![изображение](https://user-images.githubusercontent.com/13800244/195281503-22614a52-811b-49e9-ba49-8ed3b3eadb46.png)

2022-10-12 07:50 UTC, olgapshen commented on dal.cpp
> +    }
Обязательно надо обрабатывать неучтённые варианты, тк enum может пополниться, и тк в плюсах через enum можно передать любой int.

Тут стоит или кинуть ошибку: else { throw std::invalid_argument("Invalid argument .. "); } или выбрать одну из двух сортировок по умолчанию.

2022-10-12 07:50 UTC, olgapshen commented on dal.cpp
>          for (size_t i = 0; i < result.size(); ++i) {
Ладно, оставим этот код закоментированным на будущее, потом применим его для сортировки данных уже после ваыборки и обработки в плюсасх.

2022-10-12 07:50 UTC, olgapshen commented on main.cpp
> +                sortingType = sortByAddress;
Как уже писала выше, нужно обрабатывать такие случаи. В будущем тут выдадим страницу помощи в консоли, а пока можно или кинуть ошибку или установить какое то значение по умолчанию.

2022-10-12 07:50 UTC, olgapshen commented on main.cpp
> -
Молодец, что убрал пустые пробелы.

2022-10-12 07:57 UTC, olgapshen commented on dal.cpp
>          for (size_t i = 0; i < result.size(); ++i) {
Тут можешь просто нажать на `Resolve conversation`, это с моей стороны был просто информативный коментарий, тут ни чего делать не надо.

2022-10-12 07:58 UTC, olgapshen commented on main.cpp
> -
Тут тоже можно просто нажать на `Resolve conversation`.

2022-10-12 07:58 UTC, olgapshen commented
Кстати у нас в Макси так же делается код ревью на Merge Request-ы.

2022-10-12 17:30 UTC, DarkHunteR73 commented on dal.cpp
>  }
Честно, даже не знал, что новая строка какое-то значение имеет

2022-10-12 17:47 UTC, DarkHunteR73 commented
Блин! Во я косяк! force push сделал

2022-10-14 07:35 UTC, olgapshen commented
> Блин! Во я косяк! force push сделал

Ни чего страшного ) тут самое время и место учится )))

2022-10-14 07:36 UTC, olgapshen commented on dal.cpp
>  }
Это древняя святая война, в которой новые строки победили )

2022-10-14 07:37 UTC, olgapshen approved these changes
Круто!!! Молодец!
Можно сливать!

2022-10-14 16:14 UTC, merged